### ISSUE TITLE
python setup.py install

### ISSUE THREAD

**Issue by IRKnyazev** [s2labres/tesseract-ml-release#7]
Hi, 
I can't install the TESSERACT package on windows. The error i get is associated with installing scipy --- ModuleNotFoundError: No module named 'numpy.distutils'.
I have made new environments and tried different ways of installation.

**Comment by awskkzl** [comment]
Hi, can you please confirm the package numpy is installed before you install scipy?

With kind regards,

Zeliang (Mark)
________________________________
From: Ivan Knyazev ***@***.***>
Sent: Monday, March 4, 2024 8:36:40 AM
To: s2labres/tesseract-ml-release ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [s2labres/tesseract-ml-release] python setup.py install (Issue #7)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi,
I can't install the TESSERACT package on windows. The error i get is associated with installing scipy --- ModuleNotFoundError: No module named 'numpy.distutils'.
I have made new environments and tried different ways of installation.

**Comment by IRKnyazev** [comment]
Hi Zeliang, 
the numpy version i had was too new. I managed to run setup.py using python 3.9 in a new conda env as opposed to python 3.12
