### ISSUE TITLE
spatial.find_optimal_train_ratio

### ISSUE THREAD

**Issue by IRKnyazev** [s2labres/tesseract-ml-release#8]
Hi again,
I am trying to use the framework's fine tuning function spatial.find_optimal_train_ratio however in its body it uses temporal.fit_predict which has not been defined anywhere in the framework. I believe the intended function to be called is evaluation.fit_predict_update.
 More generally, can you provide an example using he tuning function? Thanks!

**Comment by awskkzl** [comment]
Hi, we have fixed the naming problem in spatial.find_optimal_train_ratio function. 
For the example of how to use these functions, we have prepared every experiment script in our article in another repo and we are currently wrapping up the experiment repo. 
Please also refer to the comments in each function for how to use them.
